services:
  app:
    container_name: crossposting
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./database.db
        target: /prisma/database.db
